// All 39 official districts of Istanbul (ilçe) and their
// neighborhoods (mahalle), sourced from the public Türkiye API
// (turkiyeapi.dev, TÜİK-derived). 960 neighborhoods total.
// Used by the searchable location picker in onboarding + the
// profile editor. Do not hand-edit - regenerate from source.

export interface IstanbulDistrict {
  district: string;
  neighborhoods: string[];
}

export const ISTANBUL_DISTRICTS: readonly IstanbulDistrict[] = [
  {
    district: "Adalar",
    neighborhoods: ["Burgazada", "Heybeliada", "Kınalıada", "Maden", "Nizam"],
  },
  {
    district: "Arnavutköy",
    neighborhoods: [
      "Adnan Menderes",
      "Anadolu",
      "Arnavutköy Merkez",
      "Atatürk",
      "Baklalı",
      "Balaban",
      "Bolluca",
      "Boyalık",
      "Boğazköy Istiklal",
      "Deliklikaya",
      "Dursunköy",
      "Durusu",
      "Fatih",
      "Hacımaşlı",
      "Hadımköy",
      "Haraççı",
      "Hastane",
      "Hicret",
      "Karaburun",
      "Karlıbayır",
      "Mareşal Fevzi Çakmak",
      "Mavigöl",
      "Mehmet Akif Ersoy",
      "Mustafa Kemal Paşa",
      "Nenehatun",
      "Sazlıbosna",
      "Tayakadın",
      "Taşoluk",
      "Terkos",
      "Yassıören",
      "Yavuz Selim",
      "Yeniköy",
      "Yeşilbayır",
      "Yunus Emre",
      "Çilingir",
      "Ömerli",
      "İmrahor",
      "İslambey",
    ],
  },
  {
    district: "Ataşehir",
    neighborhoods: [
      "Atatürk",
      "Aşıkveysel",
      "Barbaros",
      "Esatpaşa",
      "Ferhatpaşa",
      "Fetih",
      "Kayışdağı",
      "Küçükbakkalköy",
      "Mevlana",
      "Mimar Sinan",
      "Mustafa Kemal",
      "Yeni Çamlıca",
      "Yenisahra",
      "Yenişehir",
      "Örnek",
      "İnönü",
      "İçerenköy",
    ],
  },
  {
    district: "Avcılar",
    neighborhoods: [
      "Ambarlı",
      "Cihangir",
      "Denizköşkler",
      "Firuzköy",
      "Gümüşpala",
      "Merkez",
      "Mustafa Kemalpaşa",
      "Tahtakale",
      "Yeşilkent",
      "Üniversite",
    ],
  },
  {
    district: "Bahçelievler",
    neighborhoods: [
      "Bahçelievler",
      "Cumhuriyet",
      "Fevzi Çakmak",
      "Hürriyet",
      "Kocasinan Merkez",
      "Siyavuşpaşa",
      "Soğanlı",
      "Yenibosna Merkez",
      "Zafer",
      "Çobançeşme",
      "Şirinevler",
    ],
  },
  {
    district: "Bakırköy",
    neighborhoods: [
      "Ataköy 1. Kısım",
      "Ataköy 2-5-6. Kısım",
      "Ataköy 3-4-11. Kısım",
      "Ataköy 7-8-9-10. Kısım",
      "Basınköy",
      "Cevizlik",
      "Kartaltepe",
      "Osmaniye",
      "Sakızağacı",
      "Yenimahalle",
      "Yeşilköy",
      "Yeşilyurt",
      "Zeytinlik",
      "Zuhuratbaba",
      "Şenlikköy",
    ],
  },
  {
    district: "Bayrampaşa",
    neighborhoods: [
      "Altıntepsi",
      "Cevatpaşa",
      "Kartaltepe",
      "Kocatepe",
      "Muratpaşa",
      "Orta",
      "Terazidere",
      "Vatan",
      "Yenidoğan",
      "Yıldırım",
      "İsmet Paşa",
    ],
  },
  {
    district: "Bağcılar",
    neighborhoods: [
      "100. Yıl",
      "15 Temmuz",
      "Barbaros",
      "Bağlar",
      "Demirkapı",
      "Fatih",
      "Fevzi Çakmak",
      "Göztepe",
      "Güneşli",
      "Hürriyet",
      "Kazım Karabekir",
      "Kemalpaşa",
      "Kirazlı",
      "Mahmutbey",
      "Merkez",
      "Sancaktepe",
      "Yavuz Selim",
      "Yenigün",
      "Yenimahalle",
      "Yıldıztepe",
      "Çınar",
      "İnönü",
    ],
  },
  {
    district: "Başakşehir",
    neighborhoods: [
      "Altınşehir",
      "Bahçeşehir 1. Kısım",
      "Bahçeşehir 2. Kısım",
      "Başak",
      "Başakşehir",
      "Güvercintepe",
      "Kayabaşı",
      "Ziya Gökalp",
      "Şahintepe",
      "Şamlar",
    ],
  },
  {
    district: "Beykoz",
    neighborhoods: [
      "Acarlar",
      "Akbaba",
      "Alibahadır",
      "Anadolu Hisarı",
      "Anadolu Kavağı",
      "Anadolufeneri",
      "Baklacı",
      "Bozhane",
      "Cumhuriyet",
      "Dereseki",
      "Elmalı",
      "Fatih",
      "Göksu",
      "Göllü",
      "Görele",
      "Göztepe",
      "Gümüşsuyu",
      "Kanlıca",
      "Kavacık",
      "Kaynarca",
      "Kılıçlı",
      "Mahmutşevketpaşa",
      "Merkez",
      "Ortaçeşme",
      "Paşabahçe",
      "Paşamandıra",
      "Polonezköy",
      "Poyrazköy",
      "Riva",
      "Rüzgarlıbahçe",
      "Soğuksu",
      "Tokatköy",
      "Yalıköy",
      "Yavuz Selim",
      "Yeni Mahalle",
      "Zerzavatçı",
      "Çamlıbahçe",
      "Çengeldere",
      "Çiftlik",
      "Çiğdem",
      "Çubuklu",
      "Örnekköy",
      "Öğümce",
      "İncirköy",
      "İshaklı",
    ],
  },
  {
    district: "Beylikdüzü",
    neighborhoods: [
      "Adnan Kahveci",
      "Barış",
      "Büyükşehir",
      "Cumhuriyet",
      "Dereağzı",
      "Gürpınar",
      "Kavaklı",
      "Marmara",
      "Sahil",
      "Yakuplu",
    ],
  },
  {
    district: "Beyoğlu",
    neighborhoods: [
      "Arap Cami",
      "Asmalı Mescit",
      "Bedrettin",
      "Bereketzade",
      "Bostan",
      "Bülbül",
      "Camiikebir",
      "Cihangir",
      "Emekyemez",
      "Evliya Çelebi",
      "Fetihtepe",
      "Firuzağa",
      "Gümüşsuyu",
      "Hacıahmet",
      "Hacımimi",
      "Halıcıoğlu",
      "Hüseyinağa",
      "Kadımehmet Efendi",
      "Kalyoncu Kulluğu",
      "Kamer Hatun",
      "Kaptanpaşa",
      "Katipmustafa Çelebi",
      "Kemankeş Karamustafapaşa",
      "Keçeci Piri",
      "Kocatepe",
      "Kulaksız",
      "Kuloğlu",
      "Küçük Piyale",
      "Kılıçali Paşa",
      "Müeyyetzade",
      "Piripaşa",
      "Piyalepaşa",
      "Pürtelaş Hasan Efendi",
      "Sururi Mehmet Efendi",
      "Sütlüce",
      "Tomtom",
      "Yahya Kahya",
      "Yenişehir",
      "Çatma Mescit",
      "Çukur",
      "Ömer Avni",
      "Örnektepe",
      "İstiklal",
      "Şahkulu",
      "Şehit Muhtar",
    ],
  },
  {
    district: "Beşiktaş",
    neighborhoods: [
      "Abbasağa",
      "Akat",
      "Arnavutköy",
      "Balmumcu",
      "Bebek",
      "Cihannüma",
      "Dikilitaş",
      "Etiler",
      "Gayrettepe",
      "Konaklar",
      "Kuruçeşme",
      "Kültür",
      "Levazım",
      "Levent",
      "Mecidiye",
      "Muradiye",
      "Nisbetiye",
      "Ortaköy",
      "Sinanpaşa",
      "Türkali",
      "Ulus",
      "Vişnezade",
      "Yıldız",
    ],
  },
  {
    district: "Büyükçekmece",
    neighborhoods: [
      "19 Mayıs",
      "Ahmediye",
      "Alkent 2000",
      "Atatürk",
      "Bahçelievler",
      "Celaliye",
      "Cumhuriyet",
      "Dizdariye",
      "Ekinoba",
      "Fatih",
      "Güzelce",
      "Hürriyet",
      "Kamiloba",
      "Karaağaç",
      "Kumburgaz",
      "Mimaroba",
      "Mimarsinan",
      "Murat Çesme",
      "Pınartepe",
      "Sinanoba",
      "Türkoba",
      "Ulus",
      "Yenimahalle",
      "Çakmaklı",
    ],
  },
  {
    district: "Esenler",
    neighborhoods: [
      "15 Temmuz",
      "Birlik",
      "Davutpaşa",
      "Fatih",
      "Fevzi Çakmak",
      "Havaalanı",
      "Kazım Karabekir",
      "Kemer",
      "Menderes",
      "Mimar Sinan",
      "Namık Kemal",
      "Nine Hatun",
      "Oruçreis",
      "Tuna",
      "Turgut Reis",
      "Yavuz Selim",
      "Çifte Havuzlar",
    ],
  },
  {
    district: "Esenyurt",
    neighborhoods: [
      "Akevler",
      "Akçaburgaz",
      "Akşemseddin",
      "Ardıçlı",
      "Atatürk",
      "Aşık Veysel",
      "Balıkyolu",
      "Barbaros Hayrettin Paşa",
      "Battalgazi",
      "Bağlarçeşme",
      "Cumhuriyet",
      "Esenkent",
      "Fatih",
      "Gökevler",
      "Güzelyurt",
      "Hürriyet",
      "Koza",
      "Mehmet Akif Ersoy",
      "Mehterçeşme",
      "Mevlana",
      "Namık Kemal",
      "Necip Fazıl Kısakürek",
      "Orhan Gazi",
      "Osmangazi",
      "Piri Reis",
      "Pınar",
      "Saadetdere",
      "Selahaddin Eyyubi",
      "Sultaniye",
      "Süleymaniye",
      "Talatpaşa",
      "Turgut Özal",
      "Yenikent",
      "Yeşilkent",
      "Yunus Emre",
      "Zafer",
      "Çınar",
      "Örnek",
      "Üçevler",
      "İncirtepe",
      "İnönü",
      "İstiklal",
      "Şehitler",
    ],
  },
  {
    district: "Eyüpsultan",
    neighborhoods: [
      "5.levent",
      "Akpınar",
      "Akşemsettin",
      "Alibeyköy",
      "Ağaçlı",
      "Defterdar",
      "Düğmeciler",
      "Emniyettepe",
      "Esentepe",
      "Göktürk Merkez",
      "Güzeltepe",
      "Işıklar",
      "Karadolap",
      "Merkez",
      "Mimar Sinan",
      "Mithatpaşa",
      "Nişancı",
      "Odayeri",
      "Pirinççi",
      "Rami Cuma",
      "Rami Yeni",
      "Sakarya",
      "Silahtarağa",
      "Topçular",
      "Yeşilpınar",
      "Çiftalan",
      "Çırçır",
      "İhsaniye",
      "İslambey",
    ],
  },
  {
    district: "Fatih",
    neighborhoods: [
      "Aksaray",
      "Akşemsettin",
      "Alemdar",
      "Ali Kuşçu",
      "Atikali",
      "Ayvansaray",
      "Balabanağa",
      "Balat",
      "Beyazıt",
      "Binbirdirek",
      "Cankurtaran",
      "Cerrahpaşa",
      "Cibali",
      "Demirtaş",
      "Derviş Ali",
      "Emin Sinan",
      "Hacı Kadın",
      "Haseki Sultan",
      "Hobyar",
      "Hoca Gıyasettin",
      "Hocapaşa",
      "Hırka-i Şerif",
      "Kalenderhane",
      "Karagümrük",
      "Katip Kasım",
      "Kemalpaşa",
      "Koca Mustafapaşa",
      "Küçük Ayasofya",
      "Mercan",
      "Mesihpaşa",
      "Mevlanakapı",
      "Mimar Hayrettin",
      "Mimar Kemalettin",
      "Molla Fenari",
      "Molla Gürani",
      "Molla Hüsrev",
      "Muhsine Hatun",
      "Nişanca",
      "Rüstempaşa",
      "Saraç Ishak",
      "Seyyid Ömer",
      "Silivrikapı",
      "Sultan Ahmet",
      "Sururi",
      "Süleymaniye",
      "Sümbül Efendi",
      "Tahtakale",
      "Taya Hatun",
      "Topkapı",
      "Yavuz Sinan",
      "Yavuz Sultan Selim",
      "Yedikule",
      "Zeyrek",
      "İskenderpaşa",
      "Şehremini",
      "Şehsuvar Bey",
    ],
  },
  {
    district: "Gaziosmanpaşa",
    neighborhoods: [
      "Barbaros Hayrettin Paşa",
      "Bağlarbaşı",
      "Fevzi Çakmak",
      "Hürriyet",
      "Karadeniz",
      "Karayolları",
      "Karlıtepe",
      "Kazım Karabekir",
      "Merkez",
      "Mevlana",
      "Pazariçi",
      "Sarıgöl",
      "Yeni Mahalle",
      "Yenidoğan",
      "Yıldıztabya",
      "Şemsipaşa",
    ],
  },
  {
    district: "Güngören",
    neighborhoods: [
      "Abdurrahman Nafiz Gürman",
      "Akıncılar",
      "Gençosman",
      "Güneştepe",
      "Güven",
      "Haznedar",
      "Mareşal Çakmak",
      "Mehmet Nesih Özmen",
      "Merkez",
      "Sanayi",
      "Tozkoparan",
    ],
  },
  {
    district: "Kadıköy",
    neighborhoods: [
      "19 Mayıs",
      "Acıbadem",
      "Bostancı",
      "Caddebostan",
      "Caferağa",
      "Dumlupınar",
      "Erenköy",
      "Eğitim",
      "Fenerbahçe",
      "Feneryolu",
      "Fikirtepe",
      "Göztepe",
      "Hasanpaşa",
      "Kozyatağı",
      "Koşuyolu",
      "Merdivenköy",
      "Osmanağa",
      "Rasimpaşa",
      "Sahrayıcedit",
      "Suadiye",
      "Zühtüpaşa",
    ],
  },
  {
    district: "Kartal",
    neighborhoods: [
      "Atalar",
      "Cevizli",
      "Cumhuriyet",
      "Esentepe",
      "Gümüşpınar",
      "Hürriyet",
      "Karlıktepe",
      "Kordonboyu",
      "Orhantepe",
      "Orta",
      "Petrol Iş",
      "Soğanlık Yeni",
      "Topselvi",
      "Uğur Mumcu",
      "Yakacık Yeni",
      "Yakacık Çarşı",
      "Yalı",
      "Yukarı",
      "Yunus",
      "Çavuşoğlu",
    ],
  },
  {
    district: "Kağıthane",
    neighborhoods: [
      "Emniyet Evleri",
      "Gültepe",
      "Gürsel",
      "Hamidiye",
      "Harmantepe",
      "Hürriyet",
      "Mehmet Akif Ersoy",
      "Merkez",
      "Nurtepe",
      "Ortabayır",
      "Seyrantepe",
      "Sultan Selim",
      "Talatpaşa",
      "Telsizler",
      "Yahya Kemal",
      "Yeşilce",
      "Çağlayan",
      "Çeliktepe",
      "Şirintepe",
    ],
  },
  {
    district: "Küçükçekmece",
    neighborhoods: [
      "Atakent",
      "Atatürk",
      "Beşyol",
      "Cennet",
      "Cumhuriyet",
      "Fatih",
      "Fevzi Çakmak",
      "Gültepe",
      "Halkalı Merkez",
      "Kanarya",
      "Kartaltepe",
      "Kemalpaşa",
      "Mehmet Akif",
      "Sultan Murat",
      "Söğütlü Çeşme",
      "Tevfikbey",
      "Yarımburgaz",
      "Yeni Mahalle",
      "Yeşilova",
      "İnönü",
      "İstasyon",
    ],
  },
  {
    district: "Maltepe",
    neighborhoods: [
      "Altayçeşme",
      "Altıntepe",
      "Aydınevler",
      "Bağlarbaşı",
      "Başıbüyük",
      "Büyükbakkalköy",
      "Cevizli",
      "Esenkent",
      "Feyzullah",
      "Fındıklı",
      "Girne",
      "Gülensu",
      "Gülsuyu",
      "Küçükyalı Merkez",
      "Yalı",
      "Zümrütevler",
      "Çınar",
      "İdealtepe",
    ],
  },
  {
    district: "Pendik",
    neighborhoods: [
      "Ahmet Yesevi",
      "Bahçelievler",
      "Ballıca",
      "Batı",
      "Doğu",
      "Dumlupınar",
      "Emirli",
      "Ertuğrul Gazi",
      "Esenler",
      "Esenyalı",
      "Fatih",
      "Fevzi Çakmak",
      "Göçbeyli",
      "Güllü Bağlar",
      "Güzelyalı",
      "Harmandere",
      "Kavakpınar",
      "Kaynarca",
      "Kurna",
      "Kurtdoğmuş",
      "Kurtköy",
      "Orhangazi",
      "Orta",
      "Ramazanoğlu",
      "Sanayi",
      "Sapan Bağları",
      "Sülüntepe",
      "Velibaba",
      "Yayalar",
      "Yeni",
      "Yenişehir",
      "Yeşilbağlar",
      "Çamlık",
      "Çamçeşme",
      "Çınardere",
      "Şeyhli",
    ],
  },
  {
    district: "Sancaktepe",
    neighborhoods: [
      "Abdurrahmangazi",
      "Akpınar",
      "Atatürk",
      "Emek",
      "Eyüp Sultan",
      "Fatih",
      "Hilal",
      "Kemal Türkler",
      "Meclis",
      "Merve",
      "Mevlana",
      "Osmangazi",
      "Paşaköy",
      "Safa",
      "Sarıgazi",
      "Veysel Karani",
      "Yenidoğan",
      "Yunus Emre",
      "İnönü",
    ],
  },
  {
    district: "Sarıyer",
    neighborhoods: [
      "Ayazağa",
      "Bahçeköy Kemer",
      "Bahçeköy Merkez",
      "Bahçeköy Yeni",
      "Baltalimanı",
      "Büyükdere",
      "Cumhuriyet",
      "Darüşşafaka",
      "Demirciköy",
      "Emirgan",
      "Fatih Sultan Mehmet",
      "Ferahevler",
      "Garipçe",
      "Gümüşdere",
      "Huzur",
      "Kazım Karabekir Paşa",
      "Kireçburnu",
      "Kocataş",
      "Kumköy (kilyos)",
      "Kısırkaya",
      "Maden",
      "Maslak",
      "Poligon",
      "Ptt Evleri",
      "Pınar",
      "Reşitpaşa",
      "Rumelifeneri",
      "Rumelihisarı",
      "Rumelikavağı",
      "Sarıyer Merkez",
      "Tarabya",
      "Uskumruköy",
      "Yeni",
      "Yeniköy",
      "Zekeriyaköy",
      "Çamlıtepe",
      "Çayırbaşı",
      "İstinye",
    ],
  },
  {
    district: "Silivri",
    neighborhoods: [
      "Akören",
      "Alibey",
      "Alipaşa",
      "Bekirli",
      "Beyciler",
      "Büyük Kılıçlı",
      "Büyük Sinekli",
      "Büyük Çavuşlu",
      "Cumhuriyet",
      "Danamandıra",
      "Değirmenköy Fevzipaşa",
      "Değirmenköy Ismetpaşa",
      "Fatih",
      "Fener",
      "Gazitepe",
      "Gümüşyaka",
      "Kadıköy",
      "Kavaklı Hürriyet",
      "Kavaklı Istiklal",
      "Kurfallı",
      "Küçük Kılıçlı",
      "Küçük Sinekli",
      "Mimar Sinan",
      "Ortaköy",
      "Piri Mehmet Paşa",
      "Sayalar",
      "Selimpaşa",
      "Semizkumlar",
      "Seymen",
      "Yeni",
      "Yolçatı",
      "Çanta Balaban",
      "Çanta Sancaktepe",
      "Çayırdere",
      "Çeltik",
    ],
  },
  {
    district: "Sultanbeyli",
    neighborhoods: [
      "Abdurrahmangazi",
      "Adil",
      "Ahmet Yesevi",
      "Akşemsettin",
      "Battalgazi",
      "Fatih",
      "Hamidiye",
      "Hasanpaşa",
      "Mecidiye",
      "Mehmet Akif",
      "Mimar Sinan",
      "Necip Fazıl",
      "Orhangazi",
      "Turgut Reis",
      "Yavuz Selim",
    ],
  },
  {
    district: "Sultangazi",
    neighborhoods: [
      "50. Yıl",
      "75. Yıl",
      "Cebeci",
      "Cumhuriyet",
      "Esentepe",
      "Eski Habipler",
      "Gazi",
      "Habibler",
      "Malkoçoğlu",
      "Sultançiftliği",
      "Uğur Mumcu",
      "Yayla",
      "Yunus Emre",
      "Zübeyde Hanım",
      "İsmetpaşa",
    ],
  },
  {
    district: "Tuzla",
    neighborhoods: [
      "Akfırat",
      "Anadolu",
      "Aydınlı",
      "Aydıntepe",
      "Cami",
      "Evliya Çelebi",
      "Fatih",
      "Mescit",
      "Mimar Sinan",
      "Orhanlı",
      "Orta",
      "Postane",
      "Tepeören",
      "Yayla",
      "İstasyon",
      "İçmeler",
      "Şifa",
    ],
  },
  {
    district: "Zeytinburnu",
    neighborhoods: [
      "Beştelsiz",
      "Gökalp",
      "Kazlıçeşme",
      "Maltepe",
      "Merkezefendi",
      "Nuripaşa",
      "Seyitnizam",
      "Sümer",
      "Telsiz",
      "Veliefendi",
      "Yenidoğan",
      "Yeşiltepe",
      "Çırpıcı",
    ],
  },
  {
    district: "Çatalca",
    neighborhoods: [
      "Akalan",
      "Atatürk",
      "Aydınlar",
      "Bahşayiş",
      "Başak",
      "Belgrat",
      "Celepköy",
      "Dağyenice",
      "Elbasan",
      "Fatih",
      "Ferhatpaşa",
      "Gökçeali",
      "Gümüşpınar",
      "Hallaçlı",
      "Hisarbeyli",
      "Kabakça",
      "Kaleiçi",
      "Kalfa",
      "Karacaköy Merkez",
      "Karamandere",
      "Kestanelik",
      "Kızılcaali",
      "Muratbey Merkez",
      "Nakkaş",
      "Oklalı",
      "Ormanlı",
      "Ovayenice",
      "Subaşı",
      "Yalıköy",
      "Yaylacık",
      "Yazlık",
      "Çakıl",
      "Çanakça",
      "Çiftlikköy",
      "Örcünlü",
      "Örencik",
      "İhsaniye",
      "İnceğiz",
      "İzzettin",
    ],
  },
  {
    district: "Çekmeköy",
    neighborhoods: [
      "Alemdağ",
      "Aydınlar",
      "Cumhuriyet",
      "Ekşioğlu",
      "Güngören",
      "Hamidiye",
      "Hüseyinli",
      "Kirazlıdere",
      "Koçullu",
      "Mehmet Akif",
      "Merkez",
      "Mimar Sinan",
      "Nişantepe",
      "Reşadiye",
      "Soğukpınar",
      "Sultançiftliği",
      "Sırapınar",
      "Taşdelen",
      "Çamlık",
      "Çatalmeşe",
      "Ömerli",
    ],
  },
  {
    district: "Ümraniye",
    neighborhoods: [
      "Adem Yavuz",
      "Altınşehir",
      "Armağanevler",
      "Atakent",
      "Atatürk",
      "Aşağı Dudullu",
      "Cemil Meriç",
      "Dumlupınar",
      "Elmalıkent",
      "Esenevler",
      "Esenkent",
      "Esenşehir",
      "Fatih Sultan Mehmet",
      "Finanskent",
      "Hekimbaşı",
      "Huzur",
      "Ihlamurkuyu",
      "Kazım Karabekir",
      "Madenler",
      "Mehmet Akif",
      "Namık Kemal",
      "Necip Fazıl",
      "Parseller",
      "Site",
      "Tantavi",
      "Tatlısu",
      "Tepeüstü",
      "Topağacı",
      "Yamanevler",
      "Yukarı Dudullu",
      "Çakmak",
      "Çamlık",
      "İnkılap",
      "İstiklal",
      "Şerifali",
    ],
  },
  {
    district: "Üsküdar",
    neighborhoods: [
      "Acıbadem",
      "Ahmediye",
      "Altunizade",
      "Aziz Mahmut Hüdayi",
      "Bahçelievler",
      "Barbaros",
      "Beylerbeyi",
      "Bulgurlu",
      "Burhaniye",
      "Cumhuriyet",
      "Ferah",
      "Güzeltepe",
      "Kandilli",
      "Kirazlıtepe",
      "Kuleli",
      "Kuzguncuk",
      "Küplüce",
      "Küçük Çamlıca",
      "Küçüksu",
      "Kısıklı",
      "Mehmet Akif Ersoy",
      "Mimar Sinan",
      "Muratreis",
      "Salacak",
      "Selami Ali",
      "Selimiye",
      "Sultantepe",
      "Valide-i Atik",
      "Yavuztürk",
      "Zeynep Kamil",
      "Çengelköy",
      "Ünalan",
      "İcadiye",
    ],
  },
  {
    district: "Şile",
    neighborhoods: [
      "Ahmetli",
      "Akçakese",
      "Alacalı",
      "Avcıkoru",
      "Ağaçdere",
      "Ağva Merkez",
      "Balibey",
      "Bozgoca",
      "Bucaklı",
      "Bıçkıdere",
      "Darlık",
      "Değirmençayırı",
      "Doğancılı",
      "Erenler",
      "Esenceli",
      "Geredeli",
      "Gökmaşlı",
      "Göksu",
      "Göçe",
      "Hacı Kasım",
      "Hacıllı",
      "Hasanlı",
      "Kabakoz",
      "Kadıköy",
      "Kalem",
      "Karabeyli",
      "Karacaköy",
      "Karakiraz",
      "Karamandere",
      "Kervansaray",
      "Korucu",
      "Kumbaba",
      "Kurfallı",
      "Kurna",
      "Kömürlük",
      "Kızılca",
      "Meşrutiyet",
      "Oruçoğlu",
      "Osmanköy",
      "Ovacık",
      "Sahilköy",
      "Satmazlı",
      "Sofular",
      "Sortullu",
      "Soğullu",
      "Teke",
      "Ulupelit",
      "Yaka",
      "Yaylalı",
      "Yazımanayır",
      "Yeniköy",
      "Yeşilvadi",
      "Çataklı",
      "Çavuş",
      "Çayırbaşı",
      "Çelebi",
      "Çengilli",
      "Üvezli",
      "İmrendere",
      "İmrenli",
      "İsaköy",
      "Şuayipli",
    ],
  },
  {
    district: "Şişli",
    neighborhoods: [
      "19 Mayıs",
      "Bozkurt",
      "Cumhuriyet",
      "Duatepe",
      "Ergenekon",
      "Esentepe",
      "Eskişehir",
      "Feriköy",
      "Fulya",
      "Gülbahar",
      "Halaskargazi",
      "Halide Edip Adıvar",
      "Halil Rıfat Paşa",
      "Harbiye",
      "Kaptanpaşa",
      "Kuştepe",
      "Mahmut Şevket Paşa",
      "Mecidiyeköy",
      "Merkez",
      "Meşrutiyet",
      "Paşa",
      "Teşvikiye",
      "Yayla",
      "İnönü",
      "İzzet Paşa",
    ],
  },
] as const;

export const ISTANBUL_DISTRICT_NAMES: readonly string[] =
  ISTANBUL_DISTRICTS.map((d) => d.district);

// Flat "Neighborhood, District" labels for a single searchable list.
export interface IstanbulPlace {
  district: string;
  neighborhood: string;
  label: string;
}

export const ISTANBUL_PLACES: readonly IstanbulPlace[] =
  ISTANBUL_DISTRICTS.flatMap((d) =>
    d.neighborhoods.map((n) => ({
      district: d.district,
      neighborhood: n,
      label: `${n}, ${d.district}`,
    })),
  );
