// Shared neighborhood list for the Istanbul map: the marker points plus the
// metadata the filter UI needs. `slug` matches the border polygons in
// public/data/neighborhood-borders.json so the filter can highlight a hood's
// real OSM boundary. Kept here (not in istanbul-map.tsx) so the map and the
// external filter bar render from one source of truth.

export interface MapNeighborhood {
  slug: string;
  name: string;
  lng: number;
  lat: number;
  vibe: string;
  side: "European" | "Asian";
  color: string;
  bgClass: string;
  labelSide: "left" | "right";
  /** True when a real OSM boundary polygon exists for this hood. */
  hasBorder: boolean;
  /**
   * "district" = one of Istanbul's 39 ilce (full-city coverage); rendered as a
   * light dot with a hover label to avoid clutter. Omitted/"spot" = a curated
   * nomad neighborhood, rendered as a labelled pill.
   */
  tier?: "district" | "spot";
}

export const mapNeighborhoods: MapNeighborhood[] = [
  {
    slug: "galata",
    name: "Galata",
    lng: 28.974,
    lat: 41.026,
    vibe: "Historic tower district, cafes, galleries, nightlife",
    side: "European",
    color: "#f39c12",
    bgClass: "bg-accent-warm text-neutral-950",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "besiktas",
    name: "Besiktas",
    lng: 29.007,
    lat: 41.043,
    vibe: "Lively waterfront, markets, great transport links",
    side: "European",
    color: "#737373",
    bgClass:
      "bg-neutral-200 text-neutral-800 dark:bg-[#3c2d24] dark:text-[#d5dce3]",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "kadikoy",
    name: "Kadikoy",
    lng: 29.027,
    lat: 40.993,
    vibe: "Calm Asian side, walkable cafes, daily rhythm hub",
    side: "Asian",
    color: "#c0392b",
    bgClass: "bg-primary-500 text-white",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "moda",
    name: "Moda",
    lng: 29.026,
    lat: 40.978,
    vibe: "Seaside promenades, quiet streets, creative scene",
    side: "Asian",
    color: "#27ae60",
    bgClass: "bg-accent-green text-white",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "uskudar",
    name: "Uskudar",
    lng: 29.015,
    lat: 41.023,
    vibe: "Traditional neighborhood, ferry hub, Bosphorus views",
    side: "Asian",
    color: "#737373",
    bgClass:
      "bg-neutral-200 text-neutral-800 dark:bg-[#3c2d24] dark:text-[#d5dce3]",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "nisantasi",
    name: "Nisantasi",
    lng: 28.988,
    lat: 41.048,
    vibe: "Polished central living, boutiques, cafes, practical errands",
    side: "European",
    color: "#27ae60",
    bgClass: "bg-accent-green text-white",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "levent",
    name: "Levent",
    lng: 29.011,
    lat: 41.077,
    vibe: "Business corridor, metro access, coworking density",
    side: "European",
    color: "#1a1a2e",
    bgClass:
      "bg-neutral-900 text-white dark:bg-neutral-200 dark:text-neutral-900",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "balat",
    name: "Balat",
    lng: 28.949,
    lat: 41.029,
    vibe: "Historic Golden Horn streets, color, character, lower rent",
    side: "European",
    color: "#c0392b",
    bgClass: "bg-primary-500 text-white",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "atasehir",
    name: "Atasehir",
    lng: 29.124,
    lat: 40.992,
    vibe: "Modern Asian-side towers, newer apartments, quiet nights",
    side: "Asian",
    color: "#f39c12",
    bgClass: "bg-accent-warm text-neutral-950",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "cihangir",
    name: "Cihangir",
    lng: 28.982,
    lat: 41.031,
    vibe: "Bohemian hillside, cafe culture, a longtime expat favourite",
    side: "European",
    color: "#27ae60",
    bgClass: "bg-accent-green text-white",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "karakoy",
    name: "Karakoy",
    lng: 28.978,
    lat: 41.024,
    vibe: "Design studios, third-wave coffee, Galataport on the water",
    side: "European",
    color: "#f39c12",
    bgClass: "bg-accent-warm text-neutral-950",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "beyoglu",
    name: "Beyoglu",
    lng: 28.979,
    lat: 41.036,
    vibe: "Istiklal buzz, galleries, nightlife - the part that never sleeps",
    side: "European",
    color: "#c0392b",
    bgClass: "bg-primary-500 text-white",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "sisli",
    name: "Sisli",
    lng: 28.987,
    lat: 41.06,
    vibe: "Central and practical - malls, clinics, metro everywhere",
    side: "European",
    color: "#737373",
    bgClass:
      "bg-neutral-200 text-neutral-800 dark:bg-[#3c2d24] dark:text-[#d5dce3]",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "maslak",
    name: "Maslak",
    lng: 29.02,
    lat: 41.108,
    vibe: "Finance and tech towers, coworking density, weekday energy",
    side: "European",
    color: "#1a1a2e",
    bgClass:
      "bg-neutral-900 text-white dark:bg-neutral-200 dark:text-neutral-900",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "bebek",
    name: "Bebek",
    lng: 29.043,
    lat: 41.077,
    vibe: "Upscale Bosphorus village, seaside walks, slow brunches",
    side: "European",
    color: "#f39c12",
    bgClass: "bg-accent-warm text-neutral-950",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "bakirkoy",
    name: "Bakirkoy",
    lng: 28.872,
    lat: 40.978,
    vibe: "Westside Marmara coast, calmer streets, lower rents",
    side: "European",
    color: "#27ae60",
    bgClass: "bg-accent-green text-white",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "caddebostan",
    name: "Caddebostan",
    lng: 29.062,
    lat: 40.963,
    vibe: "Asian-side seaside, Bagdat Caddesi shopping, dawn joggers",
    side: "Asian",
    color: "#c0392b",
    bgClass: "bg-primary-500 text-white",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "bostanci",
    name: "Bostanci",
    lng: 29.094,
    lat: 40.955,
    vibe: "Ferry and metro hub, Marmara coast, easy commutes",
    side: "Asian",
    color: "#737373",
    bgClass:
      "bg-neutral-200 text-neutral-800 dark:bg-[#3c2d24] dark:text-[#d5dce3]",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "fatih",
    name: "Fatih",
    lng: 28.949,
    lat: 41.019,
    vibe: "Historic peninsula - mosques, bazaars, deep old-city character",
    side: "European",
    color: "#1a1a2e",
    bgClass:
      "bg-neutral-900 text-white dark:bg-neutral-200 dark:text-neutral-900",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "arnavutkoy",
    name: "Arnavutkoy",
    lng: 28.7412,
    lat: 41.1845,
    vibe: "Far northwest, airport-adjacent, rural edges and new estates",
    side: "European",
    color: "#f39c12",
    bgClass: "bg-accent-warm text-neutral-950",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "avcilar",
    name: "Avcilar",
    lng: 28.7217,
    lat: 40.9799,
    vibe: "Western Marmara coast, university crowd, metrobus commute",
    side: "European",
    color: "#737373",
    bgClass:
      "bg-neutral-200 text-neutral-800 dark:bg-[#3c2d24] dark:text-[#d5dce3]",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "bagcilar",
    name: "Bagcilar",
    lng: 28.8568,
    lat: 41.0345,
    vibe: "Dense inland west, residential and working neighborhoods",
    side: "European",
    color: "#c0392b",
    bgClass: "bg-primary-500 text-white",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "bahcelievler",
    name: "Bahcelievler",
    lng: 28.8658,
    lat: 41.003,
    vibe: "Inland west, residential, metro and metrobus access",
    side: "European",
    color: "#27ae60",
    bgClass: "bg-accent-green text-white",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "basaksehir",
    name: "Basaksehir",
    lng: 28.7951,
    lat: 41.1076,
    vibe: "Newer northwest suburbs, planned estates, families",
    side: "European",
    color: "#1a1a2e",
    bgClass:
      "bg-neutral-900 text-white dark:bg-neutral-200 dark:text-neutral-900",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "bayrampasa",
    name: "Bayrampasa",
    lng: 28.9118,
    lat: 41.0346,
    vibe: "Inland by the old walls, residential, transport links",
    side: "European",
    color: "#f39c12",
    bgClass: "bg-accent-warm text-neutral-950",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "beylikduzu",
    name: "Beylikduzu",
    lng: 28.6373,
    lat: 41.0038,
    vibe: "Far west coast, modern estates, seaside parks, families",
    side: "European",
    color: "#737373",
    bgClass:
      "bg-neutral-200 text-neutral-800 dark:bg-[#3c2d24] dark:text-[#d5dce3]",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "buyukcekmece",
    name: "Buyukcekmece",
    lng: 28.5798,
    lat: 41.0217,
    vibe: "Far west lakeside and coast, weekend houses, lower density",
    side: "European",
    color: "#c0392b",
    bgClass: "bg-primary-500 text-white",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "catalca",
    name: "Catalca",
    lng: 28.4605,
    lat: 41.1437,
    vibe: "Rural far northwest, farmland and forest, village pace",
    side: "European",
    color: "#27ae60",
    bgClass: "bg-accent-green text-white",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "esenler",
    name: "Esenler",
    lng: 28.8825,
    lat: 41.0376,
    vibe: "Inland west, residential, the main intercity bus terminal",
    side: "European",
    color: "#1a1a2e",
    bgClass:
      "bg-neutral-900 text-white dark:bg-neutral-200 dark:text-neutral-900",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "esenyurt",
    name: "Esenyurt",
    lng: 28.6801,
    lat: 41.0343,
    vibe: "Far west, fast-growing dense residential, very affordable",
    side: "European",
    color: "#f39c12",
    bgClass: "bg-accent-warm text-neutral-950",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "eyupsultan",
    name: "Eyupsultan",
    lng: 28.9327,
    lat: 41.0478,
    vibe: "Golden Horn up to the northern forests, historic and green",
    side: "European",
    color: "#737373",
    bgClass:
      "bg-neutral-200 text-neutral-800 dark:bg-[#3c2d24] dark:text-[#d5dce3]",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "gaziosmanpasa",
    name: "Gaziosmanpasa",
    lng: 28.9122,
    lat: 41.0578,
    vibe: "Inland north, dense residential, working neighborhoods",
    side: "European",
    color: "#c0392b",
    bgClass: "bg-primary-500 text-white",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "gungoren",
    name: "Gungoren",
    lng: 28.8726,
    lat: 41.0253,
    vibe: "Small dense inland district, textile trade, central west",
    side: "European",
    color: "#27ae60",
    bgClass: "bg-accent-green text-white",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "kucukcekmece",
    name: "Kucukcekmece",
    lng: 28.7712,
    lat: 40.9919,
    vibe: "Western lakeside, dense and mixed, lake parks",
    side: "European",
    color: "#1a1a2e",
    bgClass:
      "bg-neutral-900 text-white dark:bg-neutral-200 dark:text-neutral-900",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "sariyer",
    name: "Sariyer",
    lng: 29.0573,
    lat: 41.1686,
    vibe: "Northern Bosphorus, forests, fishing villages, upscale coast",
    side: "European",
    color: "#f39c12",
    bgClass: "bg-accent-warm text-neutral-950",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "silivri",
    name: "Silivri",
    lng: 28.2482,
    lat: 41.0742,
    vibe: "Far western Marmara coast, summer houses, open country",
    side: "European",
    color: "#737373",
    bgClass:
      "bg-neutral-200 text-neutral-800 dark:bg-[#3c2d24] dark:text-[#d5dce3]",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "sultangazi",
    name: "Sultangazi",
    lng: 28.8614,
    lat: 41.1043,
    vibe: "Northern inland, residential, newer working districts",
    side: "European",
    color: "#c0392b",
    bgClass: "bg-primary-500 text-white",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "zeytinburnu",
    name: "Zeytinburnu",
    lng: 28.9037,
    lat: 40.9899,
    vibe: "Marmara coast by the walls, dense, coastal park, transport",
    side: "European",
    color: "#27ae60",
    bgClass: "bg-accent-green text-white",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "adalar",
    name: "Adalar",
    lng: 29.1293,
    lat: 40.8742,
    vibe: "The Princes' Islands - car-free, ferries, pine and sea",
    side: "Asian",
    color: "#1a1a2e",
    bgClass:
      "bg-neutral-900 text-white dark:bg-neutral-200 dark:text-neutral-900",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "beykoz",
    name: "Beykoz",
    lng: 29.092,
    lat: 41.1343,
    vibe: "Northern Asian Bosphorus, forests, quiet waterfront villages",
    side: "Asian",
    color: "#f39c12",
    bgClass: "bg-accent-warm text-neutral-950",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "cekmekoy",
    name: "Cekmekoy",
    lng: 29.1739,
    lat: 41.0352,
    vibe: "Northeast suburbs, forest edges, newer low-rise estates",
    side: "Asian",
    color: "#737373",
    bgClass:
      "bg-neutral-200 text-neutral-800 dark:bg-[#3c2d24] dark:text-[#d5dce3]",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "kartal",
    name: "Kartal",
    lng: 29.1857,
    lat: 40.8886,
    vibe: "Southeast Marmara coast, redeveloping, marina and metro",
    side: "Asian",
    color: "#c0392b",
    bgClass: "bg-primary-500 text-white",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "maltepe",
    name: "Maltepe",
    lng: 29.1311,
    lat: 40.9248,
    vibe: "Asian coast, long seaside park, residential, metro",
    side: "Asian",
    color: "#27ae60",
    bgClass: "bg-accent-green text-white",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "pendik",
    name: "Pendik",
    lng: 29.235,
    lat: 40.8769,
    vibe: "Far southeast, coast and Sabiha Gokcen airport, growing fast",
    side: "Asian",
    color: "#1a1a2e",
    bgClass:
      "bg-neutral-900 text-white dark:bg-neutral-200 dark:text-neutral-900",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "sancaktepe",
    name: "Sancaktepe",
    lng: 29.2289,
    lat: 40.9905,
    vibe: "Inland northeast, newer residential, expanding",
    side: "Asian",
    color: "#f39c12",
    bgClass: "bg-accent-warm text-neutral-950",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "sultanbeyli",
    name: "Sultanbeyli",
    lng: 29.2671,
    lat: 40.967,
    vibe: "Far inland southeast, affordable residential",
    side: "Asian",
    color: "#737373",
    bgClass:
      "bg-neutral-200 text-neutral-800 dark:bg-[#3c2d24] dark:text-[#d5dce3]",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "sile",
    name: "Sile",
    lng: 29.6125,
    lat: 41.1744,
    vibe: "Far Black Sea coast, beaches and forest, weekend getaway",
    side: "Asian",
    color: "#c0392b",
    bgClass: "bg-primary-500 text-white",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "tuzla",
    name: "Tuzla",
    lng: 29.3034,
    lat: 40.8162,
    vibe: "Far southeast tip, shipyards, marinas, university campuses",
    side: "Asian",
    color: "#27ae60",
    bgClass: "bg-accent-green text-white",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "umraniye",
    name: "Umraniye",
    lng: 29.0963,
    lat: 41.0256,
    vibe: "Inland Asian hub, business towers, dense residential, metro",
    side: "Asian",
    color: "#1a1a2e",
    bgClass:
      "bg-neutral-900 text-white dark:bg-neutral-200 dark:text-neutral-900",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
  {
    slug: "kagithane",
    name: "Kagithane",
    lng: 28.973,
    lat: 41.0812,
    vibe: "Central valley, fast-gentrifying, new offices near Levent",
    side: "European",
    color: "#f39c12",
    bgClass: "bg-accent-warm text-neutral-950",
    labelSide: "right",
    hasBorder: true,
    tier: "district",
  },
];
