// Shared neighborhood list for the Istanbul map: the marker points plus the
// metadata the filter UI needs. `slug` matches the border polygons in
// public/data/neighborhood-borders.json so the filter can highlight a hood's
// real OSM boundary. Kept here (not in istanbul-map.tsx) so the map and the
// external filter bar render from one source of truth.

export interface MapNeighborhood {
  slug: string;
  name: string;
  lng: number;
  lat: number;
  vibe: string;
  side: "European" | "Asian";
  color: string;
  bgClass: string;
  labelSide: "left" | "right";
  /** True when a real OSM boundary polygon exists for this hood. */
  hasBorder: boolean;
}

export const mapNeighborhoods: MapNeighborhood[] = [
  {
    slug: "galata",
    name: "Galata",
    lng: 28.974,
    lat: 41.026,
    vibe: "Historic tower district, cafes, galleries, nightlife",
    side: "European",
    color: "#f39c12",
    bgClass: "bg-accent-warm text-neutral-950",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "besiktas",
    name: "Besiktas",
    lng: 29.007,
    lat: 41.043,
    vibe: "Lively waterfront, markets, great transport links",
    side: "European",
    color: "#737373",
    bgClass:
      "bg-neutral-200 text-neutral-800 dark:bg-[#3c2d24] dark:text-[#d5dce3]",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "kadikoy",
    name: "Kadikoy",
    lng: 29.027,
    lat: 40.993,
    vibe: "Calm Asian side, walkable cafes, daily rhythm hub",
    side: "Asian",
    color: "#c0392b",
    bgClass: "bg-primary-500 text-white",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "moda",
    name: "Moda",
    lng: 29.026,
    lat: 40.978,
    vibe: "Seaside promenades, quiet streets, creative scene",
    side: "Asian",
    color: "#27ae60",
    bgClass: "bg-accent-green text-white",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "uskudar",
    name: "Uskudar",
    lng: 29.015,
    lat: 41.023,
    vibe: "Traditional neighborhood, ferry hub, Bosphorus views",
    side: "Asian",
    color: "#737373",
    bgClass:
      "bg-neutral-200 text-neutral-800 dark:bg-[#3c2d24] dark:text-[#d5dce3]",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "nisantasi",
    name: "Nisantasi",
    lng: 28.988,
    lat: 41.048,
    vibe: "Polished central living, boutiques, cafes, practical errands",
    side: "European",
    color: "#27ae60",
    bgClass: "bg-accent-green text-white",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "levent",
    name: "Levent",
    lng: 29.011,
    lat: 41.077,
    vibe: "Business corridor, metro access, coworking density",
    side: "European",
    color: "#1a1a2e",
    bgClass:
      "bg-neutral-900 text-white dark:bg-neutral-200 dark:text-neutral-900",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "balat",
    name: "Balat",
    lng: 28.949,
    lat: 41.029,
    vibe: "Historic Golden Horn streets, color, character, lower rent",
    side: "European",
    color: "#c0392b",
    bgClass: "bg-primary-500 text-white",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "atasehir",
    name: "Atasehir",
    lng: 29.124,
    lat: 40.992,
    vibe: "Modern Asian-side towers, newer apartments, quiet nights",
    side: "Asian",
    color: "#f39c12",
    bgClass: "bg-accent-warm text-neutral-950",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "cihangir",
    name: "Cihangir",
    lng: 28.982,
    lat: 41.031,
    vibe: "Bohemian hillside, cafe culture, a longtime expat favourite",
    side: "European",
    color: "#27ae60",
    bgClass: "bg-accent-green text-white",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "karakoy",
    name: "Karakoy",
    lng: 28.978,
    lat: 41.024,
    vibe: "Design studios, third-wave coffee, Galataport on the water",
    side: "European",
    color: "#f39c12",
    bgClass: "bg-accent-warm text-neutral-950",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "beyoglu",
    name: "Beyoglu",
    lng: 28.979,
    lat: 41.036,
    vibe: "Istiklal buzz, galleries, nightlife - the part that never sleeps",
    side: "European",
    color: "#c0392b",
    bgClass: "bg-primary-500 text-white",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "sisli",
    name: "Sisli",
    lng: 28.987,
    lat: 41.06,
    vibe: "Central and practical - malls, clinics, metro everywhere",
    side: "European",
    color: "#737373",
    bgClass:
      "bg-neutral-200 text-neutral-800 dark:bg-[#3c2d24] dark:text-[#d5dce3]",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "maslak",
    name: "Maslak",
    lng: 29.02,
    lat: 41.108,
    vibe: "Finance and tech towers, coworking density, weekday energy",
    side: "European",
    color: "#1a1a2e",
    bgClass:
      "bg-neutral-900 text-white dark:bg-neutral-200 dark:text-neutral-900",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "bebek",
    name: "Bebek",
    lng: 29.043,
    lat: 41.077,
    vibe: "Upscale Bosphorus village, seaside walks, slow brunches",
    side: "European",
    color: "#f39c12",
    bgClass: "bg-accent-warm text-neutral-950",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "bakirkoy",
    name: "Bakirkoy",
    lng: 28.872,
    lat: 40.978,
    vibe: "Westside Marmara coast, calmer streets, lower rents",
    side: "European",
    color: "#27ae60",
    bgClass: "bg-accent-green text-white",
    labelSide: "right",
    hasBorder: true,
  },
  {
    slug: "caddebostan",
    name: "Caddebostan",
    lng: 29.062,
    lat: 40.963,
    vibe: "Asian-side seaside, Bagdat Caddesi shopping, dawn joggers",
    side: "Asian",
    color: "#c0392b",
    bgClass: "bg-primary-500 text-white",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "bostanci",
    name: "Bostanci",
    lng: 29.094,
    lat: 40.955,
    vibe: "Ferry and metro hub, Marmara coast, easy commutes",
    side: "Asian",
    color: "#737373",
    bgClass:
      "bg-neutral-200 text-neutral-800 dark:bg-[#3c2d24] dark:text-[#d5dce3]",
    labelSide: "left",
    hasBorder: true,
  },
  {
    slug: "fatih",
    name: "Fatih",
    lng: 28.949,
    lat: 41.019,
    vibe: "Historic peninsula - mosques, bazaars, deep old-city character",
    side: "European",
    color: "#1a1a2e",
    bgClass:
      "bg-neutral-900 text-white dark:bg-neutral-200 dark:text-neutral-900",
    labelSide: "right",
    hasBorder: true,
  },
];
