// All world nationalities (demonym + country + flag + ISO-2),
// sourced from the REST Countries API. Used by the searchable
// nationality picker in onboarding + the profile editor. The
// stored value is the demonym (e.g. "Turkish"). Regenerate from
// source rather than hand-editing.

export interface Nationality {
  code: string;
  flag: string;
  country: string;
  demonym: string;
}

export const NATIONALITIES: readonly Nationality[] = [
  { code: "AF", flag: "🇦🇫", country: "Afghanistan", demonym: "Afghan" },
  { code: "AL", flag: "🇦🇱", country: "Albania", demonym: "Albanian" },
  { code: "DZ", flag: "🇩🇿", country: "Algeria", demonym: "Algerian" },
  {
    code: "MP",
    flag: "🇲🇵",
    country: "Northern Mariana Islands",
    demonym: "American",
  },
  { code: "US", flag: "🇺🇸", country: "United States", demonym: "American" },
  {
    code: "UM",
    flag: "🇺🇲",
    country: "United States Minor Outlying Islands",
    demonym: "American Islander",
  },
  {
    code: "AS",
    flag: "🇦🇸",
    country: "American Samoa",
    demonym: "American Samoan",
  },
  { code: "AD", flag: "🇦🇩", country: "Andorra", demonym: "Andorran" },
  { code: "AO", flag: "🇦🇴", country: "Angola", demonym: "Angolan" },
  { code: "AI", flag: "🇦🇮", country: "Anguilla", demonym: "Anguillian" },
  { code: "AQ", flag: "🇦🇶", country: "Antarctica", demonym: "Antarctican" },
  {
    code: "AG",
    flag: "🇦🇬",
    country: "Antigua and Barbuda",
    demonym: "Antiguan, Barbudan",
  },
  { code: "AR", flag: "🇦🇷", country: "Argentina", demonym: "Argentine" },
  { code: "AM", flag: "🇦🇲", country: "Armenia", demonym: "Armenian" },
  { code: "AW", flag: "🇦🇼", country: "Aruba", demonym: "Aruban" },
  { code: "AU", flag: "🇦🇺", country: "Australia", demonym: "Australian" },
  { code: "AT", flag: "🇦🇹", country: "Austria", demonym: "Austrian" },
  { code: "AZ", flag: "🇦🇿", country: "Azerbaijan", demonym: "Azerbaijani" },
  { code: "BS", flag: "🇧🇸", country: "Bahamas", demonym: "Bahamian" },
  { code: "BH", flag: "🇧🇭", country: "Bahrain", demonym: "Bahraini" },
  { code: "BD", flag: "🇧🇩", country: "Bangladesh", demonym: "Bangladeshi" },
  { code: "BB", flag: "🇧🇧", country: "Barbados", demonym: "Barbadian" },
  { code: "BY", flag: "🇧🇾", country: "Belarus", demonym: "Belarusian" },
  { code: "BE", flag: "🇧🇪", country: "Belgium", demonym: "Belgian" },
  { code: "BZ", flag: "🇧🇿", country: "Belize", demonym: "Belizean" },
  { code: "BJ", flag: "🇧🇯", country: "Benin", demonym: "Beninese" },
  { code: "BM", flag: "🇧🇲", country: "Bermuda", demonym: "Bermudian" },
  { code: "BT", flag: "🇧🇹", country: "Bhutan", demonym: "Bhutanese" },
  { code: "BO", flag: "🇧🇴", country: "Bolivia", demonym: "Bolivian" },
  {
    code: "BA",
    flag: "🇧🇦",
    country: "Bosnia and Herzegovina",
    demonym: "Bosnian, Herzegovinian",
  },
  {
    code: "BV",
    flag: "🇧🇻",
    country: "Bouvet Island",
    demonym: "Bouvet Island",
  },
  { code: "BR", flag: "🇧🇷", country: "Brazil", demonym: "Brazilian" },
  { code: "GB", flag: "🇬🇧", country: "United Kingdom", demonym: "British" },
  { code: "BN", flag: "🇧🇳", country: "Brunei", demonym: "Bruneian" },
  { code: "BG", flag: "🇧🇬", country: "Bulgaria", demonym: "Bulgarian" },
  { code: "BF", flag: "🇧🇫", country: "Burkina Faso", demonym: "Burkinabe" },
  { code: "MM", flag: "🇲🇲", country: "Myanmar", demonym: "Burmese" },
  { code: "BI", flag: "🇧🇮", country: "Burundi", demonym: "Burundian" },
  { code: "KH", flag: "🇰🇭", country: "Cambodia", demonym: "Cambodian" },
  { code: "CM", flag: "🇨🇲", country: "Cameroon", demonym: "Cameroonian" },
  { code: "CA", flag: "🇨🇦", country: "Canada", demonym: "Canadian" },
  { code: "CV", flag: "🇨🇻", country: "Cape Verde", demonym: "Cape Verdian" },
  { code: "KY", flag: "🇰🇾", country: "Cayman Islands", demonym: "Caymanian" },
  {
    code: "CF",
    flag: "🇨🇫",
    country: "Central African Republic",
    demonym: "Central African",
  },
  { code: "TD", flag: "🇹🇩", country: "Chad", demonym: "Chadian" },
  { code: "GG", flag: "🇬🇬", country: "Guernsey", demonym: "Channel Islander" },
  { code: "JE", flag: "🇯🇪", country: "Jersey", demonym: "Channel Islander" },
  { code: "CL", flag: "🇨🇱", country: "Chile", demonym: "Chilean" },
  { code: "CN", flag: "🇨🇳", country: "China", demonym: "Chinese" },
  {
    code: "CX",
    flag: "🇨🇽",
    country: "Christmas Island",
    demonym: "Christmas Islander",
  },
  {
    code: "CC",
    flag: "🇨🇨",
    country: "Cocos (Keeling) Islands",
    demonym: "Cocos Islander",
  },
  { code: "CO", flag: "🇨🇴", country: "Colombia", demonym: "Colombian" },
  { code: "KM", flag: "🇰🇲", country: "Comoros", demonym: "Comoran" },
  { code: "CD", flag: "🇨🇩", country: "DR Congo", demonym: "Congolese" },
  {
    code: "CG",
    flag: "🇨🇬",
    country: "Republic of the Congo",
    demonym: "Congolese",
  },
  { code: "CK", flag: "🇨🇰", country: "Cook Islands", demonym: "Cook Islander" },
  { code: "CR", flag: "🇨🇷", country: "Costa Rica", demonym: "Costa Rican" },
  { code: "HR", flag: "🇭🇷", country: "Croatia", demonym: "Croatian" },
  { code: "CU", flag: "🇨🇺", country: "Cuba", demonym: "Cuban" },
  { code: "CW", flag: "🇨🇼", country: "Curaçao", demonym: "Curaçaoan" },
  { code: "CY", flag: "🇨🇾", country: "Cyprus", demonym: "Cypriot" },
  { code: "CZ", flag: "🇨🇿", country: "Czechia", demonym: "Czech" },
  { code: "DK", flag: "🇩🇰", country: "Denmark", demonym: "Danish" },
  { code: "DJ", flag: "🇩🇯", country: "Djibouti", demonym: "Djibouti" },
  { code: "DM", flag: "🇩🇲", country: "Dominica", demonym: "Dominican" },
  {
    code: "DO",
    flag: "🇩🇴",
    country: "Dominican Republic",
    demonym: "Dominican",
  },
  {
    code: "BQ",
    flag: "🇧🇶",
    country: "Caribbean Netherlands",
    demonym: "Dutch",
  },
  { code: "NL", flag: "🇳🇱", country: "Netherlands", demonym: "Dutch" },
  { code: "TL", flag: "🇹🇱", country: "Timor-Leste", demonym: "East Timorese" },
  { code: "EC", flag: "🇪🇨", country: "Ecuador", demonym: "Ecuadorean" },
  { code: "EG", flag: "🇪🇬", country: "Egypt", demonym: "Egyptian" },
  {
    code: "AE",
    flag: "🇦🇪",
    country: "United Arab Emirates",
    demonym: "Emirati",
  },
  {
    code: "GQ",
    flag: "🇬🇶",
    country: "Equatorial Guinea",
    demonym: "Equatorial Guinean",
  },
  { code: "ER", flag: "🇪🇷", country: "Eritrea", demonym: "Eritrean" },
  { code: "EE", flag: "🇪🇪", country: "Estonia", demonym: "Estonian" },
  { code: "ET", flag: "🇪🇹", country: "Ethiopia", demonym: "Ethiopian" },
  {
    code: "FK",
    flag: "🇫🇰",
    country: "Falkland Islands",
    demonym: "Falkland Islander",
  },
  { code: "FO", flag: "🇫🇴", country: "Faroe Islands", demonym: "Faroese" },
  { code: "FJ", flag: "🇫🇯", country: "Fiji", demonym: "Fijian" },
  { code: "PH", flag: "🇵🇭", country: "Philippines", demonym: "Filipino" },
  { code: "FI", flag: "🇫🇮", country: "Finland", demonym: "Finnish" },
  { code: "FR", flag: "🇫🇷", country: "France", demonym: "French" },
  {
    code: "TF",
    flag: "🇹🇫",
    country: "French Southern and Antarctic Lands",
    demonym: "French",
  },
  {
    code: "PF",
    flag: "🇵🇫",
    country: "French Polynesia",
    demonym: "French Polynesian",
  },
  { code: "GA", flag: "🇬🇦", country: "Gabon", demonym: "Gabonese" },
  { code: "GM", flag: "🇬🇲", country: "Gambia", demonym: "Gambian" },
  { code: "GE", flag: "🇬🇪", country: "Georgia", demonym: "Georgian" },
  { code: "DE", flag: "🇩🇪", country: "Germany", demonym: "German" },
  { code: "GH", flag: "🇬🇭", country: "Ghana", demonym: "Ghanaian" },
  { code: "GI", flag: "🇬🇮", country: "Gibraltar", demonym: "Gibraltar" },
  { code: "GR", flag: "🇬🇷", country: "Greece", demonym: "Greek" },
  { code: "GL", flag: "🇬🇱", country: "Greenland", demonym: "Greenlandic" },
  { code: "GD", flag: "🇬🇩", country: "Grenada", demonym: "Grenadian" },
  { code: "GP", flag: "🇬🇵", country: "Guadeloupe", demonym: "Guadeloupian" },
  { code: "GU", flag: "🇬🇺", country: "Guam", demonym: "Guamanian" },
  { code: "GT", flag: "🇬🇹", country: "Guatemala", demonym: "Guatemalan" },
  { code: "GF", flag: "🇬🇫", country: "French Guiana", demonym: "Guianan" },
  {
    code: "GW",
    flag: "🇬🇼",
    country: "Guinea-Bissau",
    demonym: "Guinea-Bissauan",
  },
  { code: "GN", flag: "🇬🇳", country: "Guinea", demonym: "Guinean" },
  { code: "GY", flag: "🇬🇾", country: "Guyana", demonym: "Guyanese" },
  { code: "HT", flag: "🇭🇹", country: "Haiti", demonym: "Haitian" },
  {
    code: "HM",
    flag: "🇭🇲",
    country: "Heard Island and McDonald Islands",
    demonym: "Heard and McDonald Islander",
  },
  { code: "HN", flag: "🇭🇳", country: "Honduras", demonym: "Honduran" },
  { code: "HK", flag: "🇭🇰", country: "Hong Kong", demonym: "Hong Konger" },
  { code: "HU", flag: "🇭🇺", country: "Hungary", demonym: "Hungarian" },
  { code: "KI", flag: "🇰🇮", country: "Kiribati", demonym: "I-Kiribati" },
  { code: "IS", flag: "🇮🇸", country: "Iceland", demonym: "Icelander" },
  {
    code: "IO",
    flag: "🇮🇴",
    country: "British Indian Ocean Territory",
    demonym: "Indian",
  },
  { code: "IN", flag: "🇮🇳", country: "India", demonym: "Indian" },
  { code: "ID", flag: "🇮🇩", country: "Indonesia", demonym: "Indonesian" },
  { code: "IR", flag: "🇮🇷", country: "Iran", demonym: "Iranian" },
  { code: "IQ", flag: "🇮🇶", country: "Iraq", demonym: "Iraqi" },
  { code: "IE", flag: "🇮🇪", country: "Ireland", demonym: "Irish" },
  { code: "IL", flag: "🇮🇱", country: "Israel", demonym: "Israeli" },
  { code: "IT", flag: "🇮🇹", country: "Italy", demonym: "Italian" },
  { code: "CI", flag: "🇨🇮", country: "Ivory Coast", demonym: "Ivorian" },
  { code: "JM", flag: "🇯🇲", country: "Jamaica", demonym: "Jamaican" },
  { code: "JP", flag: "🇯🇵", country: "Japan", demonym: "Japanese" },
  { code: "JO", flag: "🇯🇴", country: "Jordan", demonym: "Jordanian" },
  { code: "KZ", flag: "🇰🇿", country: "Kazakhstan", demonym: "Kazakhstani" },
  { code: "KE", flag: "🇰🇪", country: "Kenya", demonym: "Kenyan" },
  { code: "KG", flag: "🇰🇬", country: "Kyrgyzstan", demonym: "Kirghiz" },
  {
    code: "KN",
    flag: "🇰🇳",
    country: "Saint Kitts and Nevis",
    demonym: "Kittitian or Nevisian",
  },
  { code: "XK", flag: "🇽🇰", country: "Kosovo", demonym: "Kosovar" },
  { code: "KW", flag: "🇰🇼", country: "Kuwait", demonym: "Kuwaiti" },
  { code: "LA", flag: "🇱🇦", country: "Laos", demonym: "Laotian" },
  { code: "LV", flag: "🇱🇻", country: "Latvia", demonym: "Latvian" },
  { code: "LB", flag: "🇱🇧", country: "Lebanon", demonym: "Lebanese" },
  { code: "LR", flag: "🇱🇷", country: "Liberia", demonym: "Liberian" },
  { code: "LY", flag: "🇱🇾", country: "Libya", demonym: "Libyan" },
  {
    code: "LI",
    flag: "🇱🇮",
    country: "Liechtenstein",
    demonym: "Liechtensteiner",
  },
  { code: "LT", flag: "🇱🇹", country: "Lithuania", demonym: "Lithuanian" },
  { code: "LU", flag: "🇱🇺", country: "Luxembourg", demonym: "Luxembourger" },
  { code: "MO", flag: "🇲🇴", country: "Macau", demonym: "Macanese" },
  { code: "MK", flag: "🇲🇰", country: "North Macedonia", demonym: "Macedonian" },
  { code: "YT", flag: "🇾🇹", country: "Mayotte", demonym: "Mahoran" },
  { code: "MG", flag: "🇲🇬", country: "Madagascar", demonym: "Malagasy" },
  { code: "MW", flag: "🇲🇼", country: "Malawi", demonym: "Malawian" },
  { code: "MY", flag: "🇲🇾", country: "Malaysia", demonym: "Malaysian" },
  { code: "MV", flag: "🇲🇻", country: "Maldives", demonym: "Maldivan" },
  { code: "ML", flag: "🇲🇱", country: "Mali", demonym: "Malian" },
  { code: "MT", flag: "🇲🇹", country: "Malta", demonym: "Maltese" },
  { code: "IM", flag: "🇮🇲", country: "Isle of Man", demonym: "Manx" },
  {
    code: "MH",
    flag: "🇲🇭",
    country: "Marshall Islands",
    demonym: "Marshallese",
  },
  { code: "MQ", flag: "🇲🇶", country: "Martinique", demonym: "Martinican" },
  { code: "MR", flag: "🇲🇷", country: "Mauritania", demonym: "Mauritanian" },
  { code: "MU", flag: "🇲🇺", country: "Mauritius", demonym: "Mauritian" },
  { code: "MX", flag: "🇲🇽", country: "Mexico", demonym: "Mexican" },
  { code: "FM", flag: "🇫🇲", country: "Micronesia", demonym: "Micronesian" },
  { code: "MD", flag: "🇲🇩", country: "Moldova", demonym: "Moldovan" },
  { code: "MC", flag: "🇲🇨", country: "Monaco", demonym: "Monegasque" },
  { code: "MN", flag: "🇲🇳", country: "Mongolia", demonym: "Mongolian" },
  { code: "ME", flag: "🇲🇪", country: "Montenegro", demonym: "Montenegrin" },
  { code: "MS", flag: "🇲🇸", country: "Montserrat", demonym: "Montserratian" },
  { code: "MA", flag: "🇲🇦", country: "Morocco", demonym: "Moroccan" },
  { code: "LS", flag: "🇱🇸", country: "Lesotho", demonym: "Mosotho" },
  { code: "BW", flag: "🇧🇼", country: "Botswana", demonym: "Motswana" },
  { code: "MZ", flag: "🇲🇿", country: "Mozambique", demonym: "Mozambican" },
  { code: "NA", flag: "🇳🇦", country: "Namibia", demonym: "Namibian" },
  { code: "NR", flag: "🇳🇷", country: "Nauru", demonym: "Nauruan" },
  { code: "NP", flag: "🇳🇵", country: "Nepal", demonym: "Nepalese" },
  {
    code: "NC",
    flag: "🇳🇨",
    country: "New Caledonia",
    demonym: "New Caledonian",
  },
  { code: "NZ", flag: "🇳🇿", country: "New Zealand", demonym: "New Zealander" },
  { code: "VU", flag: "🇻🇺", country: "Vanuatu", demonym: "Ni-Vanuatu" },
  { code: "NI", flag: "🇳🇮", country: "Nicaragua", demonym: "Nicaraguan" },
  { code: "NG", flag: "🇳🇬", country: "Nigeria", demonym: "Nigerian" },
  { code: "NE", flag: "🇳🇪", country: "Niger", demonym: "Nigerien" },
  { code: "NU", flag: "🇳🇺", country: "Niue", demonym: "Niuean" },
  {
    code: "NF",
    flag: "🇳🇫",
    country: "Norfolk Island",
    demonym: "Norfolk Islander",
  },
  { code: "KP", flag: "🇰🇵", country: "North Korea", demonym: "North Korean" },
  {
    code: "SJ",
    flag: "🇸🇯",
    country: "Svalbard and Jan Mayen",
    demonym: "Norwegian",
  },
  { code: "NO", flag: "🇳🇴", country: "Norway", demonym: "Norwegian" },
  { code: "OM", flag: "🇴🇲", country: "Oman", demonym: "Omani" },
  { code: "PK", flag: "🇵🇰", country: "Pakistan", demonym: "Pakistani" },
  { code: "PW", flag: "🇵🇼", country: "Palau", demonym: "Palauan" },
  { code: "PS", flag: "🇵🇸", country: "Palestine", demonym: "Palestinian" },
  { code: "PA", flag: "🇵🇦", country: "Panama", demonym: "Panamanian" },
  {
    code: "PG",
    flag: "🇵🇬",
    country: "Papua New Guinea",
    demonym: "Papua New Guinean",
  },
  { code: "PY", flag: "🇵🇾", country: "Paraguay", demonym: "Paraguayan" },
  { code: "PE", flag: "🇵🇪", country: "Peru", demonym: "Peruvian" },
  {
    code: "PN",
    flag: "🇵🇳",
    country: "Pitcairn Islands",
    demonym: "Pitcairn Islander",
  },
  { code: "PL", flag: "🇵🇱", country: "Poland", demonym: "Polish" },
  { code: "PT", flag: "🇵🇹", country: "Portugal", demonym: "Portuguese" },
  { code: "PR", flag: "🇵🇷", country: "Puerto Rico", demonym: "Puerto Rican" },
  { code: "QA", flag: "🇶🇦", country: "Qatar", demonym: "Qatari" },
  { code: "RO", flag: "🇷🇴", country: "Romania", demonym: "Romanian" },
  { code: "RU", flag: "🇷🇺", country: "Russia", demonym: "Russian" },
  { code: "RW", flag: "🇷🇼", country: "Rwanda", demonym: "Rwandan" },
  { code: "RE", flag: "🇷🇪", country: "Réunion", demonym: "Réunionese" },
  { code: "EH", flag: "🇪🇭", country: "Western Sahara", demonym: "Sahrawi" },
  {
    code: "BL",
    flag: "🇧🇱",
    country: "Saint Barthélemy",
    demonym: "Saint Barthélemy Islander",
  },
  {
    code: "SH",
    flag: "🇸🇭",
    country: "Saint Helena, Ascension and Tristan da Cunha",
    demonym: "Saint Helenian",
  },
  { code: "LC", flag: "🇱🇨", country: "Saint Lucia", demonym: "Saint Lucian" },
  {
    code: "MF",
    flag: "🇲🇫",
    country: "Saint Martin",
    demonym: "Saint Martin Islander",
  },
  {
    code: "VC",
    flag: "🇻🇨",
    country: "Saint Vincent and the Grenadines",
    demonym: "Saint Vincentian",
  },
  {
    code: "PM",
    flag: "🇵🇲",
    country: "Saint Pierre and Miquelon",
    demonym: "Saint-Pierrais, Miquelonnais",
  },
  { code: "SV", flag: "🇸🇻", country: "El Salvador", demonym: "Salvadoran" },
  { code: "SM", flag: "🇸🇲", country: "San Marino", demonym: "Sammarinese" },
  { code: "WS", flag: "🇼🇸", country: "Samoa", demonym: "Samoan" },
  {
    code: "ST",
    flag: "🇸🇹",
    country: "São Tomé and Príncipe",
    demonym: "Sao Tomean",
  },
  { code: "SA", flag: "🇸🇦", country: "Saudi Arabia", demonym: "Saudi Arabian" },
  { code: "SN", flag: "🇸🇳", country: "Senegal", demonym: "Senegalese" },
  { code: "RS", flag: "🇷🇸", country: "Serbia", demonym: "Serbian" },
  { code: "SC", flag: "🇸🇨", country: "Seychelles", demonym: "Seychellois" },
  {
    code: "SL",
    flag: "🇸🇱",
    country: "Sierra Leone",
    demonym: "Sierra Leonean",
  },
  { code: "SG", flag: "🇸🇬", country: "Singapore", demonym: "Singaporean" },
  { code: "SK", flag: "🇸🇰", country: "Slovakia", demonym: "Slovak" },
  { code: "SI", flag: "🇸🇮", country: "Slovenia", demonym: "Slovene" },
  {
    code: "SB",
    flag: "🇸🇧",
    country: "Solomon Islands",
    demonym: "Solomon Islander",
  },
  { code: "SO", flag: "🇸🇴", country: "Somalia", demonym: "Somali" },
  { code: "ZA", flag: "🇿🇦", country: "South Africa", demonym: "South African" },
  {
    code: "GS",
    flag: "🇬🇸",
    country: "South Georgia",
    demonym: "South Georgian South Sandwich Islander",
  },
  { code: "KR", flag: "🇰🇷", country: "South Korea", demonym: "South Korean" },
  { code: "SS", flag: "🇸🇸", country: "South Sudan", demonym: "South Sudanese" },
  { code: "ES", flag: "🇪🇸", country: "Spain", demonym: "Spanish" },
  { code: "LK", flag: "🇱🇰", country: "Sri Lanka", demonym: "Sri Lankan" },
  { code: "SX", flag: "🇸🇽", country: "Sint Maarten", demonym: "St. Maartener" },
  { code: "SD", flag: "🇸🇩", country: "Sudan", demonym: "Sudanese" },
  { code: "SR", flag: "🇸🇷", country: "Suriname", demonym: "Surinamer" },
  { code: "SZ", flag: "🇸🇿", country: "Eswatini", demonym: "Swazi" },
  { code: "SE", flag: "🇸🇪", country: "Sweden", demonym: "Swedish" },
  { code: "CH", flag: "🇨🇭", country: "Switzerland", demonym: "Swiss" },
  { code: "SY", flag: "🇸🇾", country: "Syria", demonym: "Syrian" },
  { code: "TJ", flag: "🇹🇯", country: "Tajikistan", demonym: "Tadzhik" },
  { code: "TW", flag: "🇹🇼", country: "Taiwan", demonym: "Taiwanese" },
  { code: "TZ", flag: "🇹🇿", country: "Tanzania", demonym: "Tanzanian" },
  { code: "TH", flag: "🇹🇭", country: "Thailand", demonym: "Thai" },
  { code: "TG", flag: "🇹🇬", country: "Togo", demonym: "Togolese" },
  { code: "TK", flag: "🇹🇰", country: "Tokelau", demonym: "Tokelauan" },
  { code: "TO", flag: "🇹🇴", country: "Tonga", demonym: "Tongan" },
  {
    code: "TT",
    flag: "🇹🇹",
    country: "Trinidad and Tobago",
    demonym: "Trinidadian",
  },
  { code: "TN", flag: "🇹🇳", country: "Tunisia", demonym: "Tunisian" },
  { code: "TR", flag: "🇹🇷", country: "Turkey", demonym: "Turkish" },
  { code: "TM", flag: "🇹🇲", country: "Turkmenistan", demonym: "Turkmen" },
  {
    code: "TC",
    flag: "🇹🇨",
    country: "Turks and Caicos Islands",
    demonym: "Turks and Caicos Islander",
  },
  { code: "TV", flag: "🇹🇻", country: "Tuvalu", demonym: "Tuvaluan" },
  { code: "UG", flag: "🇺🇬", country: "Uganda", demonym: "Ugandan" },
  { code: "UA", flag: "🇺🇦", country: "Ukraine", demonym: "Ukrainian" },
  { code: "UY", flag: "🇺🇾", country: "Uruguay", demonym: "Uruguayan" },
  { code: "UZ", flag: "🇺🇿", country: "Uzbekistan", demonym: "Uzbekistani" },
  { code: "VA", flag: "🇻🇦", country: "Vatican City", demonym: "Vatican" },
  { code: "VE", flag: "🇻🇪", country: "Venezuela", demonym: "Venezuelan" },
  { code: "VN", flag: "🇻🇳", country: "Vietnam", demonym: "Vietnamese" },
  {
    code: "VI",
    flag: "🇻🇮",
    country: "United States Virgin Islands",
    demonym: "Virgin Islander",
  },
  {
    code: "VG",
    flag: "🇻🇬",
    country: "British Virgin Islands",
    demonym: "Virgin Islander",
  },
  {
    code: "WF",
    flag: "🇼🇫",
    country: "Wallis and Futuna",
    demonym: "Wallis and Futuna Islander",
  },
  { code: "YE", flag: "🇾🇪", country: "Yemen", demonym: "Yemeni" },
  { code: "ZM", flag: "🇿🇲", country: "Zambia", demonym: "Zambian" },
  { code: "ZW", flag: "🇿🇼", country: "Zimbabwe", demonym: "Zimbabwean" },
  { code: "AX", flag: "🇦🇽", country: "Åland Islands", demonym: "Ålandish" },
] as const;
